apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcat
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
        tier: frontend
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0.12-jre10
        ports:
        - containerPort: 80 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
      nodeSelector:
        tier: web
